module.exports = {
    Themes: {
        Default: {
            Name: "Default",
            SafeColor: "#672D34",
            Color: "#000000",
            Accent: "#DA0406",
            BorderColor: "#3F3136",
            NotFilledColor: "#3F3136",
            HPColor: "#DA0406",
            XPColor: "#B4B5A2",
            BackgroundBlur: 40,
            PolarGraphFill: "#3CA057",
            PolarGraphForm: "circular",
            PolarGraphLabelShadow: "#FFFFFF",
            SoftFont: "./src/assets/fonts/BreeSerif-Regular.ttf",
            MainFont: "./src/assets/fonts/LuxuriousRoman-Regular.ttf",
            DisplayFont: "./src/assets/fonts/bloodcrow.ttf",
            BackgroundImage: "./src/assets/images/themes/BackgroundImageDefault.png",
            AvatarBorder: "./src/assets/images/themes/AvatarBorderDefault.png",
            DefaultMale: "./src/assets/images/themes/MaleDefault.png",
            DefaultFemale: "./src/assets/images/themes/FemaleDefault.png",
            HeartImage: "./src/assets/images/themes/HeartDefault.png",
            MaskImage: "./src/assets/images/themes/MaskDefault.png",
            StatsImage: "./src/assets/images/themes/StatsDefault.png",
            MascotImage: "./src/assets/images/themes/MascotDefault.png",
        },
    },
    Rpg: {
        Databases: {
            Activity: "🥏",
            Additional: "📊",
            Inventory: "🎒",
            Map: "🌍",
            Player: "👺",
            Quest: "📜",
            Squad: "🥋",
        },
        Concepts: {
            DemonBlood: "🩸",
            SlayerQuest: "🎴",
            SideQuest: "👺",
            DailyQuest: "📆",
            Notifications: "🔔",
        },
    },
    Systems: {
        Grades: {
            Tester: "🔬",
            Admin: "🔑",
            Owner: "👘",
        },
        Symbols: {
            Check: "✅",
            Cross: "❌",
            Previous: "◀️",
            Next: "▶️",
        },
        Status: {
            Online: "🟢",
            Maintenance: "🚧",
            Disabled: "❗",
        },
    },
    Colors: {
        Blurple: 0x5865f2,
        Green: 0x44c767,
        Red: 0xf04747,
    },
    Units: {
        MinutesPerDistanceUnit: 5,
        MinutesOfForgingPerRarity: 120,
    },
    Images: {
        Character0: "https://cdn.discordapp.com/attachments/980577808243900446/1037877260201504918/MC_ObanaiBot.png",
        Character1: "https://cdn.discordapp.com/attachments/980577808243900446/1038086907088879666/Female_MC_ObanaiBot.png",
    },
};